### ISSUE TITLE
Using android-3D-model-viewer as library

### ISSUE THREAD

**Issue by alvinfong06** [the3deer/android-3D-model-viewer#237]
Hi, I'm currently developing a photogrammetry application where you take 2D images and turn them into 3D mesh models in STL formats. If I were to use this as a library for my application in Android Studio, how do I proceed? I currently have my 3D mesh model in STL files and trying to visualize it using this library in Android Studio.

**Comment by andresoviedo** [comment]
Hi @alvinfong06 .  You have 2 modules (app + engine).  
So you can build your own Viewer using the engine as you want.  
I think the viewer code has all you need in order to import your own STL models. 

This piece of code launches a ModelFragment using an URI an input
You can make that URI point to your either http public url, android asset or android content manager link.

https://github.com/the3deer/android-3D-model-viewer/blob/75bc656afd814baec8d0acbda419bf80fa584dec/app/src/main/java/org/the3deer/app/model3D/view/LoadDialogFragment.java#L561

Regards
